server:
  port: 8081

logging:
  level:
    org:
    springframework: INFO
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest

kafka:
  topic:
    server: localhost:9092
    name: kafka_topic
    group_id: kafka_group